/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const SsoCallbackIndexLazyImport = createFileRoute('/sso-callback/')()
const SignUpIndexLazyImport = createFileRoute('/sign-up/')()
const SignInIndexLazyImport = createFileRoute('/sign-in/')()
const ChatIndexLazyImport = createFileRoute('/chat/')()
const AuthCallbackIndexLazyImport = createFileRoute('/auth-callback/')()
const AdminIndexLazyImport = createFileRoute('/admin/')()
const AlbumAlbumIdIndexLazyImport = createFileRoute('/album/$albumId/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SsoCallbackIndexLazyRoute = SsoCallbackIndexLazyImport.update({
  id: '/sso-callback/',
  path: '/sso-callback/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/sso-callback/index.lazy').then((d) => d.Route),
)

const SignUpIndexLazyRoute = SignUpIndexLazyImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-up/index.lazy').then((d) => d.Route))

const SignInIndexLazyRoute = SignInIndexLazyImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in/index.lazy').then((d) => d.Route))

const ChatIndexLazyRoute = ChatIndexLazyImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chat/index.lazy').then((d) => d.Route))

const AuthCallbackIndexLazyRoute = AuthCallbackIndexLazyImport.update({
  id: '/auth-callback/',
  path: '/auth-callback/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth-callback/index.lazy').then((d) => d.Route),
)

const AdminIndexLazyRoute = AdminIndexLazyImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))

const AlbumAlbumIdIndexLazyRoute = AlbumAlbumIdIndexLazyImport.update({
  id: '/album/$albumId/',
  path: '/album/$albumId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/album/$albumId/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth-callback/': {
      id: '/auth-callback/'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sso-callback/': {
      id: '/sso-callback/'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/album/$albumId/': {
      id: '/album/$albumId/'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/auth-callback': typeof AuthCallbackIndexLazyRoute
  '/chat': typeof ChatIndexLazyRoute
  '/sign-in': typeof SignInIndexLazyRoute
  '/sign-up': typeof SignUpIndexLazyRoute
  '/sso-callback': typeof SsoCallbackIndexLazyRoute
  '/album/$albumId': typeof AlbumAlbumIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/auth-callback': typeof AuthCallbackIndexLazyRoute
  '/chat': typeof ChatIndexLazyRoute
  '/sign-in': typeof SignInIndexLazyRoute
  '/sign-up': typeof SignUpIndexLazyRoute
  '/sso-callback': typeof SsoCallbackIndexLazyRoute
  '/album/$albumId': typeof AlbumAlbumIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/auth-callback/': typeof AuthCallbackIndexLazyRoute
  '/chat/': typeof ChatIndexLazyRoute
  '/sign-in/': typeof SignInIndexLazyRoute
  '/sign-up/': typeof SignUpIndexLazyRoute
  '/sso-callback/': typeof SsoCallbackIndexLazyRoute
  '/album/$albumId/': typeof AlbumAlbumIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth-callback'
    | '/chat'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/album/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth-callback'
    | '/chat'
    | '/sign-in'
    | '/sign-up'
    | '/sso-callback'
    | '/album/$albumId'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/auth-callback/'
    | '/chat/'
    | '/sign-in/'
    | '/sign-up/'
    | '/sso-callback/'
    | '/album/$albumId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
  AuthCallbackIndexLazyRoute: typeof AuthCallbackIndexLazyRoute
  ChatIndexLazyRoute: typeof ChatIndexLazyRoute
  SignInIndexLazyRoute: typeof SignInIndexLazyRoute
  SignUpIndexLazyRoute: typeof SignUpIndexLazyRoute
  SsoCallbackIndexLazyRoute: typeof SsoCallbackIndexLazyRoute
  AlbumAlbumIdIndexLazyRoute: typeof AlbumAlbumIdIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
  AuthCallbackIndexLazyRoute: AuthCallbackIndexLazyRoute,
  ChatIndexLazyRoute: ChatIndexLazyRoute,
  SignInIndexLazyRoute: SignInIndexLazyRoute,
  SignUpIndexLazyRoute: SignUpIndexLazyRoute,
  SsoCallbackIndexLazyRoute: SsoCallbackIndexLazyRoute,
  AlbumAlbumIdIndexLazyRoute: AlbumAlbumIdIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin/",
        "/auth-callback/",
        "/chat/",
        "/sign-in/",
        "/sign-up/",
        "/sso-callback/",
        "/album/$albumId/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.lazy.tsx"
    },
    "/auth-callback/": {
      "filePath": "auth-callback/index.lazy.tsx"
    },
    "/chat/": {
      "filePath": "chat/index.lazy.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.lazy.tsx"
    },
    "/sign-up/": {
      "filePath": "sign-up/index.lazy.tsx"
    },
    "/sso-callback/": {
      "filePath": "sso-callback/index.lazy.tsx"
    },
    "/album/$albumId/": {
      "filePath": "album/$albumId/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
